name: acme.sh addon for Home Assistant
version: "2024.11.1"
slug: acme-sh
image: "ghcr.io/djelibeybi/homeassistant-acme.sh-addon-{arch}"
description: >-
  This addon uses acme.sh and its DNS provider plugins to issue and renew SSL certificates.
url: https://github.com/Djelibeybi/homeassistant-acme.sh-addon
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
map:
  - ssl:rw
hassio_api: true
hassio_role: manager
init: false
options:
  accountemail: null
  acmeprovider: zerossl
  domains: null
  dnsprovider: null
  dnschallengealias: ""
  dnsenvvars:
    - name: null
      value: null
  keylength: "4096"
  fullchainfile: fullchain.pem
  keyfile: privkey.pem
schema:
  accountemail: str
  acmeprovider: list(letsencrypt|letsencrypt_test|buypass|buypass_test|zerossl|sslcom|google|googletest)
  domains:
    - str
  dnsprovider: str
  dnschallengealias: str?
  dnsenvvars:
    - name: str
      value: str
  keylength: list(2048|4096|ec-256|ec-384|ec-512)
  fullchainfile: str
  keyfile: str
